config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'beading-news', to: 'pages#beading_news'
  
  resources :blogs do
    member do 
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'
  
  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p class="app-footer"><%= copyright_generator %></p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Welcome</h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= copyright_generator %>
  </p>
  <p>
    <a href="#">Back To Top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">Beading Brena's Jewelry Blog</h1>
    <p class="lead blog-description">Read my blogs here!</p>
      <span>
      <%= link_to 'Create A New Blog', new_blog_path, class: 'btn btn-secondary' if logged_in?(:site_admin) %>
      </span>
      <span>
        <%= link_to 'Sort Blogs By Topics', topics_path, class: 'btn btn-secondary' %>
      </span>      
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded blog-nav">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="container">
    <%= link_to "Beading Brena's Jewelry", root_path, class: 'navbar-brand' %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <%= nav_helper 'nav-link', 'li' %>  
        <%= login_helper 'nav-link' %>  
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Here, you can view my blogs about new updates. To post blogs, you must become a site admin
     by getting ahold of me by means of the contact page. I will be as quick as I
    can to email back as long as you qualify. To qualify, you must be a Beading Brena's Jewelry
    employee. Do not abuse the right to be a site admin. I can take it away at any time I feel
    necessary. Also, to post comments on blogs, you must create an account and be logged in. Thank you.</p>
  </div>
  
    <%= source_helper("alert alert-info blog-sidebar-source") %>
  
  <div class="sidebar-module">
    <h4>Topics</h4>
    <% @side_bar_topics.each do |topic| %>
      <p><%= link_to topic.title, topic_path(topic) %></p>
    <% end %>
  </div>
    
  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://twitter.com/BrenaBSuit"><%= fa_icon "twitter" %></a></li>  
      <li><a href="https://www.google.com/search?q=facebook&rlz=1C1GGRV_enUS751US751&oq=facebook&aqs=chrome..69i57j0l5.1271j0j7&sourceid=chrome&ie=UTF-8"><%= fa_icon "facebook" %></a></li> 
      <li><a href="https://www.google.com/search?q=instagram&rlz=1C1GGRV_enUS751US751&oq=instagram&aqs=chrome..69i57j0l5.1279j0j7&sourceid=chrome&ie=UTF-8"><%= fa_icon "instagram" %></a></li>
    </ol>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About Me", about_me_path %></div>
  <div><%= link_to "Contact Me", contact_path %></div>
  <div><%= link_to "Blog", blogs_path %></div>
  <div><%= link_to "Portfolios", portfolios_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "View All Portfolio Items", portfolios_path, class: "btn btn-primary" %>   
      <a href="#", class="btn btn-primary">Back To Top</a>
    </p>
    <p>
      <%= copyright_generator %>
    </p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Beading Brena's Jewelry Portfolio</h1>
    <p class="lead text-muted">This is where you can view examples of my products and my tools. I will keep this page updated at all times.</p>
    <p>
      <%= link_to 'Home Page', root_path, class: 'btn btn-primary' %>
      <%= link_to 'Find Out More About Me', about_me_path, class: 'btn btn-primary' %>
      <%= link_to 'My Blog', blogs_path, class: 'btn btn-primary' %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-inverse" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">On this portfolio page, you can view information about my business;
        including projects I've done, and other items. You can also find information
        on the tools I have, such as beads, string, and colors. I will keep this page updated with anything
        new I create. I'm sorry that the pictures do not work at school. They will work as long as they
        have a connection to Imgur. Thank you!</p>
        
      </div>
      <div class="col-sm-4 py-4">
        <h3 class="text-white">Explore</h3>
        <ul class="list-unstyled">
          <%= nav_helper 'text-white', 'li' %>
          <li><%= login_helper 'text-white' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="navbar navbar-inverse bg-inverse">
  <div class="container d-flex justify-content-between">
    <h1>
      <a href="#" class="navbar-brand">Beading Brena's Jewelry</a>
    </h1>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>